apiVersion: v1
kind: ConfigMap
metadata:
  name: globus-proxy-config
data:
  globus-proxy-config.json: |-
    {
      "primary_site_admin_tenant_base_url": "{{globus_primary_site_admin_tenant_base_url}}",
      "service_site_id": "{{globus_proxy_site_id}}",
      "service_tenant_id": "{{globus_proxy_tenant_id}}",
      "service_name": "{{globus_proxy_name}}",
      "log_level": "{{globus_proxy_log_level}}",
      "tenants": {{globus_proxy_tenants|to_json}},
      "show_traceback": {{globus_proxy_show_traceback|to_json}},
      "use_sk": true,
      "client_id": "{{ globus_client_id }}",
      "client_secret": "{{ globus_client_secret }}"
    }

