apiVersion: batch/v1
kind: Job
metadata:
  name: mlhub-federated-identities-migrator
spec:
  backoffLimit: 0
  template:
    metadata:
      name: mlhub-federated-identities-migrator
    spec:
      restartPolicy: Never
      containers:
        - env:
            - name: MONGO_HOST
              value: mlhub-mongo-stateful-set-0.mlhub-mongo-headless-service.default.svc.cluster.local
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_NAME
              value: mlhub
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlhub-secrets
                  key: mongo-user-password
            - name: MONGO_USERNAME
              value: mlhub
            - name: MONGO_REPLICA_SET
              value: rs0
            - name: RABBIT_HOST
              value: mlhub-rabbit-service
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlhub-secrets
                  key: rabbit-password
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: dev
            - name: RUST_LOG
              value: debug
            - name: SHARED_DATA
              value: /srv/mlhub
          image: {{ mlhub_federated_identity_migrator_image }}
          imagePullPolicy: Always
          name: federated-identities-migrator
          resources: {}
