#!/bin/bash

# Set up configmap for streams and kapacitor
kubectl apply -f ../streams-config.yml
kubectl apply -f ../kapacitor-config.yml

kubectl apply -f pvc.yml
kubectl apply -f deploy.yml
kubectl apply -f service.yml 
