#!/bin/bash

set -e 

# global Tapis burnup script

# Helps run all the components in the correct order

# sorting out some script coordinates
mydir_absolute=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
myscript_nameonly="$( basename -- "${BASH_SOURCE[0]}" )"
myscript_absolute="$mydir_absolute/$myscript_nameonly"

# uncomment for debug 
#echo $mydir_absolute
#echo $myscript_nameonly
#echo $myscript_absolute


burnup_or_exit () {
  echo "Burnup: $1" 
  cd $mydir_absolute/$1 || exit 1
  ./burnup || exit 1
  cd $mydir_absolute || exit 1
  echo "Done: $1" 
  return 0
}


echo "Start: top-level-burnup"

mkdir -p {{ tapisdatadir }}

{%- if "tapisflavor" == "docker" %}
### Docker-specific setup 
docker network inspect tapis || docker network create tapis 
{% endif %}


### init / setup

{% if "proxy" in components_to_deploy %}
burnup_or_exit proxy
{% endif %}

{% if "vault" in components_to_deploy %}
burnup_or_exit vault
{% endif %}

{% if "skadmin" in components_to_deploy%}
burnup_or_exit skadmin
{% endif %}


### primary services

{% if "tenants" in components_to_deploy %}
burnup_or_exit tenants
{% endif %}

{% if "security" in components_to_deploy %}
burnup_or_exit security
{% endif %}

{% if "tokens" in components_to_deploy %}
burnup_or_exit tokens
{% endif %}

{% if "authenticator" in components_to_deploy %}
burnup_or_exit authenticator
{% endif %}


### secondary services

{% if "jobs" in components_to_deploy %}
burnup_or_exit jobs  
{% endif %}

{% if "files" in components_to_deploy %}
burnup_or_exit files
{% endif %}

{% if "systems" in components_to_deploy %}
burnup_or_exit systems
{% endif %}



echo "Done: top-level-burnup"

exit 0
