#!/bin/bash


# global Tapis burndown script

# Helps run all the components in the correct order

# sorting out some script coordinates
mydir_absolute=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
myscript_nameonly="$( basename -- "${BASH_SOURCE[0]}" )"
myscript_absolute="$mydir_absolute/$myscript_nameonly"

# uncomment for debug 
#echo $mydir_absolute
#echo $myscript_nameonly
#echo $myscript_absolute

# burn down in reverse order
echo "Start: top-level-burndown"

### tertiary services

# actors

# container-registry

# globus-proxy

{% if "meta" in components_to_deploy %}
cd $mydir_absolute/meta
./burndown
{% endif %}

# monitoring

{% if "notifications" in components_to_deploy %}
cd $mydir_absolute/notifications
./burndown
{% endif %}

# pgrest

# pgrest-a2cps-dev

# pgrest-a2cps-prod

# pods

{% if "streams" in components_to_deploy %}
cd $mydir_absolute/streams
./burndown streams
{% endif %}

{% if "tapisui" in components_to_deploy %}
cd $mydir_absolute/tapisui
./burndown
{% endif %}

# workflows

### secondary services

{% if "jobs" in components_to_deploy %}
cd $mydir_absolute/jobs
./burndown
{% endif %}

{% if "files" in components_to_deploy %}
cd $mydir_absolute/files
./burndown
{% endif %}

{% if "systems" in components_to_deploy %}
cd $mydir_absolute/systems
./burndown
{% endif %}

{% if "apps" in components_to_deploy %}
cd $mydir_absolute/apps
./burndown
{% endif %}

### primary services

{% if "tenants" in components_to_deploy %}
cd $mydir_absolute/tenants
./burndown
{% endif %}

{% if "security" in components_to_deploy %}
cd $mydir_absolute/security
./burndown
{% endif %}

{% if "tokens" in components_to_deploy %}
cd $mydir_absolute/tokens
./burndown
{% endif %}

{% if "authenticator" in components_to_deploy %}
cd $mydir_absolute/authenticator
./burndown
{% endif %}

### init

# {% if "skadmin" in components_to_deploy%}
# cd $mydir_absolute/skadmin
# ./burndown
# {% endif %}

{% if "vault" in components_to_deploy %}
cd $mydir_absolute/vault
./burndown
{% endif %}

{% if "proxy" in components_to_deploy %}
cd $mydir_absolute/proxy
./burndown
{% endif %}

echo "Done: top-level-burndown"

exit 0
