#!/bin/bash

set -e 

# global Tapis burndown script

# Helps run all the components in the correct order

# sorting out some script coordinates
mydir_absolute=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
myscript_nameonly="$( basename -- "${BASH_SOURCE[0]}" )"
myscript_absolute="$mydir_absolute/$myscript_nameonly"

# uncomment for debug 
#echo $mydir_absolute
#echo $myscript_nameonly
#echo $myscript_absolute


echo "Start: top-level-burndown"

{% if "proxy" in components_to_deploy %}
cd $mydir_absolute/proxy
./burndown
{% endif %}

{% if "vault" in components_to_deploy %}
cd $mydir_absolute/vault
./burndown
{% endif %}

{% if "skadmin" in components_to_deploy%}
cd $mydir_absolute/skadmin
./burndown
{% endif %}


### primary services

{% if "tenants" in components_to_deploy %}
cd $mydir_absolute/tenants
./burndown
{% endif %}

{% if "security" in components_to_deploy %}
cd $mydir_absolute/security
./burndown
{% endif %}

{% if "tokens" in components_to_deploy %}
cd $mydir_absolute/tokens
./burndown
{% endif %}

{% if "authenticator" in components_to_deploy %}
cd $mydir_absolute/authenticator
./burndown
{% endif %}


### secondary services

{% if "jobs" in components_to_deploy %}
cd $mydir_absolute/jobs
./burndown
{% endif %}

{% if "files" in components_to_deploy %}
cd $mydir_absolute/files
./burndown
{% endif %}

{% if "systems" in components_to_deploy %}
cd $mydir_absolute/systems
./burndown
{% endif %}



echo "Done: top-level-burndown"

exit 0
