#!/bin/bash
# Script to initialize Apps service DB using psql
# Create database, user and schema
# Postgres password must be set in env var POSTGRES_PASSWORD

if [ -z "$DB_HOST" ]; then
  DB_HOST=apps-postgres-16
fi

DB_USER=postgres
DB_NAME=tapisappdb

if [ -z "${POSTGRES_PASSWORD}" ]; then
  echo "Please set env var POSTGRES_PASSWORD before running this script"
  exit 1
fi

# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${POSTGRES_PASSWORD}

# Run psql command to create database if it does not exist
echo "SELECT 'CREATE DATABASE ${DB_NAME} ENCODING=\"UTF8\" LC_COLLATE=\"en_US.utf8\" LC_CTYPE=\"en_US.utf8\" ' \
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec" \
  | psql --host=${DB_HOST} --username=${DB_USER}


# Run sql to create user and schema if they do not exist
psql --host=${DB_HOST} --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE tapis_app WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: tapis_app';
END
\$\$;
ALTER USER tapis_app WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE tapisappdb TO tapis_app;

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS tapis_app AUTHORIZATION tapis_app;
ALTER ROLE tapis_app SET search_path = 'tapis_app';
EOB

{% if apps_monitor_password is defined and apps_monitor_password %}
# this is the password :{{ apps_monitor_password }}
# end

### hammock/mpackard 20210616


# Script to add Monitoring read only access for Apps service DB using psql
# user and grant read only acces
# Postgres password must be set in env var MONITOR_PASSWORD

if [ -z "${MONITOR_PASSWORD}" ]; then
  echo "Please set env var MONITOR_PASSWORD before running this script"
  exit 1
fi

# Run sql to create user if it does not exist
psql --host=${DB_HOST} --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE monitor WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: monitor';
END
\$\$;
ALTER USER monitor WITH ENCRYPTED PASSWORD '${MONITOR_PASSWORD}';
GRANT SELECT ON ALL TABLES IN SCHEMA tapis_app TO monitor;
GRANT CONNECT ON DATABASE tapisappdb TO monitor;
GRANT USAGE ON SCHEMA tapis_app TO monitor;

EOB
{% endif %}
