#!/bin/bash

echo "burnup apps:"

mkdir -p {{ tapisdatadir }}/apps
myuid=`id -u`
export UID=`id -u`
export GID=`id -g`

docker run -it --rm -v {{ tapisdatadir }}/apps:/apps tapis/ubutil2204:1.3.0 chown $myuid /apps

python3 {{ tapisdir }}/admin/util/parse_skexport -c apps -d {{ tapisdatadir }}

docker compose up -d

