#!/bin/bash

echo "burnup apps:"

mkdir -p {{ tapisdatadir }}/apps
mkdir -p {{ tapisdatadir }}/apps/postgres

python3 ../admin/util/parse_skexport -c apps -d {{ tapisdatadir }}

docker compose up -d

