#!/bin/bash

echo "burnup systems:"

mkdir -p {{ tapisdatadir }}/systems
myuid=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/systems:/systems tapis/ubutil2204:1.4.0 chown $myuid /systems

export UID=`id -u`
export GID=`id -g`
python3 {{ tapisdir }}/admin/util/parse_skexport -c systems -d {{ tapisdatadir }}

docker-compose up -d

