#!/bin/bash

echo "burnup systems:"

mkdir -p {{ tapisdatadir }}/systems
mkdir -p {{ tapisdatadir }}/systems/postgres

MYUID=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/systems:/systems tapis/ubutil2204:1.4.0 chown $MYUID /systems

export UID_GID="$(id -u):$(id -g)"

python3 ../admin/util/parse_skexport -c systems -d {{ tapisdatadir }}

docker compose up -d

