#!/bin/sh
#
# Do a full burnup for the Notifications service
#

echo "notifications:"

here=`pwd`

cd $here
kubectl apply -f notifications-config.yml


# Deploy postgres and api

cd $here/postgres
./burnup

cd $here/api
./burnup
