#!/bin/sh
#
# Do a full non-destructive burndown for the Notifications service
#

echo "notifications:"

here=`pwd`

 
# UnDeploy api and postgres
 
cd $here/api
./burndown

cd $here/dispatcher
./burndown

cd $here/rabbitmq
./burndown

cd $here/postgres
./burndown

cd $here
kubectl delete -f notifications-config.yml
