#!/bin/bash

echo "burnup notifications:"

mkdir -p {{ tapisdatadir }}/notifications
myuid=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/notifications:/notifications tapis/ubutil2204:1.3.0 chown $myuid /notifications

python3 {{ tapisdir }}/admin/util/parse_skexport -c notifications -d {{ tapisdatadir }}

docker compose up -d