#!/bin/bash

echo "burnup notifications:"

mkdir -p {{ tapisdatadir }}/notifications
mkdir -p {{ tapisdatadir }}/notifications/postgres

python3 ../admin/util/parse_skexport -c notifications -d {{ tapisdatadir }}

docker compose up -d
