#!/bin/bash

echo burnup streams

mkdir -p {{ tapisdatadir }}/streams/influx
mkdir -p {{ tapisdatadir }}/streams/mysql/data
mkdir -p {{ tapisdatadir }}/streams/grafana/data

export MYUID="$(id -u)"
export UID_GID="$(id -u):$(id -g)"

docker run -it --rm -v {{ tapisdatadir }}/streams:/streams tapis/ubutil2204:1.3.0 chown $MYUID /streams

python3 {{ tapisdir }}/admin/util/parse_skexport -c streams -d {{ tapisdatadir }}

docker compose up -d