#!/bin/bash


mkdir -p {{ tapisdatadir }}/streams
mkdir -p {{ tapisdatadir }}/streams/influx
mkdir -p {{ tapisdatadir }}/streams/mysql

myuid=`id -u`
export UID=`id -u`
export GID=`id -g`

docker run -it --rm -v {{ tapisdatadir }}/streams:/streams tapis/ubutil2204:1.3.0 chown $myuid /streams

python3 {{ tapisdir }}/admin/util/parse_skexport -c streams -d {{ tapisdatadir }}

docker compose up -d