#!/bin/bash

# Set up configmap for jobs
kubectl apply -f ../jobs-config.yml

kubectl apply -f pvc-postgres.yml
kubectl apply -f service.yml
kubectl apply -f deploy.yml
kubectl apply -f pgadmin.yml

# Wait for postgres to finish coming up
kubectl wait --timeout=120s --for=condition=available deploy/jobs-postgres-16

# Initialize the DB
# First, remove any artifacts from a previous run
kubectl delete -f jobs-init-db.yml
kubectl delete configmap jobs-init-db-configmap
# Run the init script
kubectl create configmap jobs-init-db-configmap --from-file jobs-init-db-sh
kubectl create -f jobs-init-db.yml
kubectl wait --timeout=120s --for=condition=complete job/jobs-init-db

