#!/bin/bash
# Script to initialize service DB using psql
# Create database, user and schema
# Postgres password must be set in env var POSTGRES_PASSWORD and Tapis specific user password
#   must be set in TAPIS_DB_PASSWORD

if [ -z "$TAPIS_DB_HOST" ]; then
  TAPIS_DB_HOST=jobs-postgres-16
fi

if [ -z "$TAPIS_DB_PORT" ]; then
  TAPIS_DB_PORT=5432
fi

PSQL_CMD="psql --host=${TAPIS_DB_HOST} --port=${TAPIS_DB_PORT}"

DB_NAME=tapisjobsdb
PG_DB_USER=postgres
export TAPIS_DB_USER=tapis
export TAPIS_DB_SCHEMA=tapis_jobs
export TAPIS_OLD_SCHEMA=public

if [ -z "${POSTGRES_PASSWORD}" ]; then
  echo "Please set env var POSTGRES_PASSWORD before running this script"
  exit 1
fi

if [ -z "${TAPIS_DB_PASSWORD}" ]; then
  echo "Please set env var TAPIS_DB_PASSWORD before running this script"
  exit 1
fi

# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${POSTGRES_PASSWORD}

#
# Run psql command to create database if it does not exist
#
echo "SELECT 'CREATE DATABASE ${DB_NAME} ENCODING=\"UTF8\" LC_COLLATE=\"en_US.utf8\" LC_CTYPE=\"en_US.utf8\" ' \
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec" \
  | $PSQL_CMD --username=${PG_DB_USER}

#
# Run sql to create user and schema if they do not exist
#
$PSQL_CMD --username=${PG_DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE ${TAPIS_DB_USER} WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: ${TAPIS_DB_USER}';
END
\$\$;
ALTER USER ${TAPIS_DB_USER} WITH ENCRYPTED PASSWORD '${TAPIS_DB_PASSWORD}';

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS ${TAPIS_DB_SCHEMA} AUTHORIZATION ${TAPIS_DB_USER};
EOB
# Make sure user has full access to public and tapis_jobs schemas
$PSQL_CMD --username=${PG_DB_USER} --dbname=${DB_NAME} -q << EOB
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${TAPIS_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${TAPIS_DB_SCHEMA} TO ${TAPIS_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${TAPIS_OLD_SCHEMA} TO ${TAPIS_DB_USER};
ALTER ROLE ${TAPIS_DB_USER} SET search_path = '${TAPIS_DB_SCHEMA}';
EOB
#
# If tables are still in old schema move them to new schema and update owner
# NOTE: This will move indexes also, but enum types must be moved separately.
# NOTE: The flyway_schema_history table is owned by the postgres user so cannot be done as part of flyway migration.
#
$PSQL_CMD --username=${PG_DB_USER} --dbname=${DB_NAME} -q << EOB
DO
\$\$DECLARE
   p_table regclass;
BEGIN
   SET LOCAL search_path='${TAPIS_OLD_SCHEMA}';
   FOR p_table IN
      SELECT oid FROM pg_class
      WHERE relnamespace = '${TAPIS_OLD_SCHEMA}'::regnamespace
        AND relkind = 'r'
   LOOP
      EXECUTE format('ALTER TABLE %s SET SCHEMA ${TAPIS_DB_SCHEMA}', p_table);
      EXECUTE format('ALTER TABLE %s OWNER TO ${TAPIS_DB_USER}', p_table);
   END LOOP;
END;\$\$;
EOB
#
# Move types from the public schema to the tapis_jobs schema and update owner
# NOTE: They are owned by the postgres user so cannot be done as part of flyway migration.
#
$PSQL_CMD --username=${PG_DB_USER} --dbname=${DB_NAME} -q << EOB
DO \$\$
DECLARE t TEXT;
BEGIN FOR t IN
  SELECT t.typname FROM pg_type t
    JOIN  pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typtype = 'e' AND n.nspname = 'public'
    AND t.typname in ('job_event_enum','job_status_enum','job_remote_outcome_enum')
  LOOP
    EXECUTE format('ALTER TYPE ${TAPIS_OLD_SCHEMA}.%s SET SCHEMA ${TAPIS_DB_SCHEMA}', t);
    EXECUTE format('ALTER TYPE ${TAPIS_DB_SCHEMA}.%s OWNER TO ${TAPIS_DB_USER}', t);
  END LOOP;
END;\$\$;
EOB
