resources:
  - ../../base
  - ../../../site-configs/overlays/minikube

patches:
  - target:
      kind: Deployment
      name: mlhub-artifact-publisher-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mlhub-artifact-publisher-deployment
      spec:
        template:
          spec:
            containers:
              - name: artifact-publisher
                image: tapis/mlhub-artifact-publisher:local
                imagePullPolicy: Never
                resources: {}