#!/bin/sh
#
# Do a full burnup for the Systems service
#

echo "systems:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/systems

# Deploy postgres and api

cd $here
kubectl apply -f systems-config.yml

cd $here/postgres
./burnup

cd $here/api
./burnup
