#!/bin/sh
#
# Do a full burndown for the Systems service
#

echo "systems:"

here=`pwd`

# UnDeploy api and postgres

cd $here/api
./burndown

cd $here/postgres_16
./burndown

cd $here
kubectl delete -f systems-config.yml
