#!/bin/bash

s=`kubectl get secret tapis-tenants-secrets -o json | jq -r '.data["service-password"]' | base64 -d`

# tokens
# should return 200 and JSON with token

curl -u "tenants:$s" -H "Content-type: application/json" -d '{"token_tenant_id": "admin", "account_type": "service", "token_username": "tenants", "target_site_id": "tacc"}'  {{admin_service_url}}/v3/tokens

