---

security_auto_service:
security_heap_max: 3G
security_heap_min: 3G
security_service_name: security
security_service_site_id: "{{ global_site_id }}"
security_service_tenant_id: admin
security_service_url: "{{ global_service_url }}"
security_postgres_pvc: sk-postgres-vol01
security_storage_class: "{{ global_storage_class }}"
security_vault_url: "{{ global_vault_url }}"
security_volumes: true
security_image_pull_policy: Always
# set to false if vault remote:
# security_renew_sk_script: true
security_renew_sk_script: false
security_primary_site_admin_tenant_base_url: "{{ global_primary_site_admin_tenant_base_url }}"
# docker-specific vars

