resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: mlhub-nfs-server-pvc
    patch: |-
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mlhub-nfs-server-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: cinder-csi
        resources:
          requests:
            storage: 200Gi