#!/bin/bash


#port=`kubectl get service sk-api -o json | jq ".spec.ports[].nodePort"`

echo

echo "readycheck"
curl {{ admin_service_url }}/v3/security/readycheck

echo

echo "healthcheck"
curl {{ admin_service_url }}/v3/security/healthcheck

echo
