# image: tapis/deployer-input-gen
# run with: 
#    docker run -v $(pwd)/output:/data -it tapis/deployer-input-gen --out=/data --start=/data/start_file.yml
FROM python:3.9

# dependencies
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# add api generator code
RUN mkdir /deploygen
ADD templates /deploygen/templates
ADD tapis-api-generator.py /deploygen/tapis-api-generator.py
ADD lib /deploygen/lib

# deployer inputgen code
ADD inputgen /inputgen

# workdir, entrypoint and command
WORKDIR /inputgen
ENTRYPOINT [ "python3", "input_generator.py" ]