# image: tapis/deployer-input-gen
# run with: 
#    docker run it --rm -v $(pwd):/data tapis/deployer-input-gen -o /data
FROM python:3.9

# dependencies
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# deployer code
ADD templates /templates
ADD input_files /input_files
ADD input_generator.py /input_generator.py

# entrypoint and command
ENTRYPOINT [ "python3", "/input_generator.py" ]