# image: tapis/deployer-input-gen
# run with: 
#    docker run -v $(pwd)/output:/data -it tapis/deployer-input-gen --out=/data --start=/data/start_file.yml
FROM python:3.9

# dependencies
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# deployer inputgen code
ADD inputgen /inputgen

# workdir, entrypoint and command
WORKDIR /inputgen
ENTRYPOINT [ "python3", "input_generator.py" ]