#!/bin/bash

echo "burnup tenants:"

mkdir -p {{ tapisdatadir }}/tenants
myuid=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/tenants:/tenants tapis/ubutil2204:1.3.0 chown $myuid /tenants
python3 {{ tapisdir }}/admin/util/parse_skexport -c tenants -d {{ tapisdatadir }}

docker compose up -d




