#!/bin/bash

echo "burnup tenants:"

# export postgres_password=`grep DBCREDENTIAL_POSTGRES_TENANTS_POSTGRES_TENANTS_TENANTS_PASSWORD {{ tapisdatadir }}/skadmin/env | awk -F= '{print $2}' | tr -d " \t\n\r"`
# export POSTGRES_PASSWORD=`grep DBCREDENTIAL_POSTGRES_TENANTS_POSTGRES_TENANTS_TENANTS_PASSWORD {{ tapisdatadir }}/skadmin/env | awk -F= '{print $2}' | tr -d " \t\n\r"`
# export service_password=`grep SERVICEPWD_TENANTS_PASSWORD {{ tapisdatadir }}/skadmin/env | awk -F= '{print $2}' | tr -d " \t\n\r"`
# # export admin_tenant_public_key=`grep JWTSIGNING_ADMIN_PUBLICKEY {{ tapisdatadir }}/skadmin/env | awk -F= '{print $2}' | base64 -w0`
# # export dev_tenant_public_key=`grep JWTSIGNING_DEV_PUBLICKEY {{ tapisdatadir }}/skadmin/env | awk -F= '{print $2}' | base64 -w0`

# export admin_tenant_public_key=$(grep JWTSIGNING_ADMIN_PUBLICKEY {{ tapisdatadir }}/skadmin/env | awk -v RS='\r\n' -FJWTSIGNING_ADMIN_PUBLICKEY= '{print $2}' | sed 's/\\n/\n/g')
# export dev_tenant_public_key=$(grep JWTSIGNING_DEV_PUBLICKEY {{ tapisdatadir }}/skadmin/env | awk -v RS='\r\n' -FJWTSIGNING_DEV_PUBLICKEY= '{print $2}' | sed 's/\\n/\n/g')

python3 {{ tapisdir }}/admin/util/parse_skexport -c tenants -d {{ tapisdatadir }}

docker compose up -d tenants-postgres

docker compose run --rm tenants-migrations upgrade

docker compose up -d tenants-api




