#!/bin/bash

echo "burnup tenants:"

mkdir -p {{ tapisdatadir }}/tenants
mkdir -p {{ tapisdatadir }}/tenants/postgres

MYUID=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/tenants:/tenants tapis/ubutil2204:1.4.0 chown $MYUID /tenants
python3 ../admin/util/parse_skexport -c tenants -d {{ tapisdatadir }}

docker compose up -d




