apiVersion: v1
kind: Service
metadata:
  name: mlhub-deployments-api-service
spec:
  type: ClusterIP
  selector:
    app: mlhub-deployments-api-deployment
  ports:
  - port: 8000
    targetPort: 8000
