#!/usr/bin/env bash

here=$(pwd)

overlay="{{ mlhub_env }}"

cd "$here/traefik"
./burndown.sh "$overlay"

cd "$here/nfs"
./burndown.sh "$overlay"

cd "$here/mongo"
./burndown.sh "$overlay"

cd "$here/rabbit"
./burndown.sh "$overlay"

cd "$here/artifact-ingester"
./burndown.sh "$overlay"

cd "$here/artifact-publisher"
./burndown.sh "$overlay"

cd "$here/models"
./burndown.sh "$overlay"