#!/usr/bin/env bash

set -e

here=$(pwd)

cd "$here/traefik"
./burndown.sh

cd "$here/nfs"
./burndown.sh

cd "$here/mongo"
./burndown.sh

cd "$here/rabbit"
./burndown.sh

cd "$here/artifact-ingester"
./burndown.sh

cd "$here/artifact-publisher"
./burndown.sh

cd "$here/models"
./burndown.sh