#!/usr/bin/env bash

set -e

echo "mlhub:"

here=$(pwd)

overlay="{{ mlhub_env }}"

cd "$here/traefik"
./burnup.sh "$overlay"

cd "$here/nfs"
./burnup.sh "$overlay"

echo "Waiting 5 seconds for nfs server to start"
sleep 5

cd "$here/mongo"
./burnup.sh "$overlay"
kubectl rollout status statefulset/mlhub-mongo-stateful-set --timeout=10m

cd "$here/rabbit"
./burnup.sh "$overlay"

echo "Waiting 5 seconds to let rabbit warm up"

cd "$here/artifact-ingester"
./burnup.sh "$overlay"

cd "$here/artifact-publisher"
./burnup.sh "$overlay"

cd "$here/model-deployment-controller"
./burnup.sh "$overlay"

echo "Waiting 5 seconds for async workers to start and connect to rabbit"
sleep 5

echo "Starting Migrations"

cd "$here/seeders/hpc-cluster-seeder"
./burnup.sh "$overlay"

cd "$here/migrations/models-migrator"
./burnup.sh "$overlay"

cd "$here/migrations/deployments-migrator"
./burnup.sh "$overlay"
kubectl wait --for=condition=complete job/mlhub-deployments-migrator --timeout=10m

cd "$here/migrations/principals-migrator"
./burnup.sh "$overlay"

cd "$here/migrations/federated-identities-migrator"
./burnup.sh "$overlay"

echo "All migrations started"

echo "Starting APIs"

cd "$here/models"
./burnup.sh "$overlay"

cd "$here/deployments"
./burnup.sh "$overlay"


echo "Starting ETL Pipelines"

cd "$here/model-etl-pipelines/hf-model-etl"
./run.sh "$overlay"

cd "$here/dataset-etl-pipelines/hf-dataset-etl"
./run.sh "$overlay"

cd "$here/datasets"
./burnup.sh "$overlay"

cd "$here/agents"
./burnup.sh "$overlay"
