# Datasources
apiVersion: v1
kind: ConfigMap
metadata:
  name: actors-nginx-config
data:
  flask-project: |-
    server {
    
        listen 80;
        server_name abaco.org;
        charset utf-8;
        resolver {{ actors_service_nginx_kube_resolver }};

        access_log /dev/stdout;
    
        location /docs {
            root /;
        }
    
        location ~* ^/v3/actors/admin(.*) {
            proxy_pass http://actors-admin.{{actors_kube_domain}}:5000/actors/admin$1$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~* ^/v3/actors/(.*)/messages(.*) {
            proxy_pass http://actors-mes.{{actors_kube_domain}}:5000/actors/$1/messages$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~ ^/v3/actors/search/(.*) {
            proxy_pass http://actors-reg.{{actors_kube_domain}}:5000/actors/search/$1$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~ /v3/actors/(.*)/workers(.*) {
            proxy_pass http://actors-admin.{{actors_kube_domain}}:5000/actors/$1/workers$2$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~ /v3/actors/aliases/(.*)/permissions {
            proxy_pass http://actors-admin.{{actors_kube_domain}}:5000/actors/aliases/$1/permissions$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~ /v3/actors/(.*)/permissions {
            proxy_pass http://actors-admin.{{actors_kube_domain}}:5000/actors/$1/permissions$is_args$args;
            proxy_set_header Host $host;
        }
    
        location ~ ^/v3/actors(.*) {
            proxy_pass http://actors-reg.{{actors_kube_domain}}:5000/actors$1$is_args$args;
            proxy_set_header Host $host;
        }
    
        # custom 400 errors:
        error_page 404  /404.json;
        location /404.json{
            root json;
        }
    
        error_page 400 401 402 403 405  /40x.json;
        location /40x.json{
            root json;
        }
    
        # custom 500 errors:
        error_page 502  /502.json;
        location /502.json{
            root json;
        }
    
        error_page 500 501 503 504 /50x.json;
        location /50x.json{
            root json;
        }
    
    }
