---
apiVersion: v1
kind: Service
metadata:
  name: actors-nginx
spec:
  type: NodePort
  selector:
    app: actors-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: actors-mongo
spec:
  type: NodePort
  selector:
    app: actors-mongo
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: actors-rabbit
spec:
  type: NodePort
  selector:
    app: actors-rabbit
  ports:
  - name: rabbit
    port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: actors-rabbit-dash
spec:
  selector:
    app: actors-rabbit
  ports:
  - name: rabbit2
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: actors-reg
spec:
  selector:
    app: actors-reg
  ports:
  - name: flask
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: actors-mes
spec:
  selector:
    app: actors-mes
  ports:
  - name: flask
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: actors-admin
spec:
  selector:
    app: actors-admin
  ports:
  - name: flask
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: actors-events
spec:
  selector:
    app: actors-events
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
