apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mongo-query-exporter.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-exporter
  name: mongo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f mongo-query-exporter.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-exporter
    spec:
      containers:
        - env:
            - name: MDBEXPORTER_MONGODB_URI
              value: mongodb://tapisadmin:changeme@mongo.example.com:27019/?authSource=admin
          image: {{ meta_mongo_exporter_image }}
          name: mongodb-query-exporter
          ports:
            - containerPort: 9412
          resources: {}
      restartPolicy: Always
status: {}
