resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: mlhub-deployments-migrator
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mlhub-deployments-migrator
      spec:
        template:
          spec:
            containers:
              - name: deployments-migrator
                image: tapis/mlhub-deployments-migrator:26Q2.1
                imagePullPolicy: Always
                resources: {}
                env:
                  - name: MONGO_HOST
                    value: mlhub-mongo-stateful-set-0.mlhub-mongo-headless-service.tapisprod.svc.cluster.local
