#!/bin/bash

echo "monitoring:"

# DO NOT burn Persistent storage
# DO NOT burn Services 

# Configs
kubectl apply -f secrets.yml 
kubectl delete -f monitoring-config.yml

# Apps
kubectl delete -f apps


