#!/bin/bash

# Set up configmap for monitoring
kubectl apply -f monitoring-config.yml

# Persistent storage
kubectl apply -f init.yml

# Configs
kubectl apply -f secrets.yml 

# Services
kubectl apply -f services.yml

# Apps
kubectl apply -f apps.yml

