---

jobs_service_name: jobs
jobs_service_site_id: "{{ global_site_id }}"
jobs_service_tenant_id: "{{ global_service_tenant_id }}"
jobs_service_url: "{{ global_service_url }}"
jobs_postgres_pvc: jobs-postgres-vol01
jobs_storage_class: "{{ global_storage_class }}"
jobs_rabbitmq_pvc: jobs-rabbitmq-vol01
jobs_node_selector: null
jobs_node_name: true
jobs_port: 8082
jobs_auditing_enabled: "{{ global_auditing_enabled }}"
