#!/bin/sh
#
# Do a full burnup for the Systems service
#

PrgName=`basename $0`

# Determine absolute path to location from which we are running.
export RUN_DIR=`pwd`
export PRG_RELPATH=`dirname $0`
cd $PRG_RELPATH/.
export PRG_PATH=`pwd`
cd $RUN_DIR

#
# Deploy postgres and api
#
kubectl apply -f systems-config.yml
cd $PRG_PATH/postgres
./burnup
cd $PRG_PATH/api
./burnup
