#!/bin/sh
#
# Do a full burndown for the Systems service
#

PrgName=`basename $0`

# Determine absolute path to location from which we are running.
export RUN_DIR=`pwd`
export PRG_RELPATH=`dirname $0`
cd $PRG_RELPATH/.
export PRG_PATH=`pwd`
cd $RUN_DIR

#
# UnDeploy api and postgres
#
cd $PRG_PATH/api
./burndown
cd $PRG_PATH/postgres
./burndown
