apiVersion: v1
kind: ConfigMap
metadata: 
  name: systems-config
data:
  "service_site_url": "{{systems_service_url}}"
  "service_tenant_id": "{{systems_service_tenant_id}}"
  "site_id": "{{systems_service_site_id}}"
  "service_name": "{{systems_service_name}}"
  "globus_client_id": "{{systems_globus_client_id}}"
