#!/bin/bash

echo "burndown authenticator:"

here=`pwd`

cd $here/authenticator/api
./burndown

cd $here/authenticator/postgres
./burndown

cd $here/authenticator/ldap
./burndown

kubectl delete -f authenticator-config.yml
