#!/bin/bash

echo "authenticator:"

here=`pwd`

# first ensure that the ./postgres/burnup script has been run because we need configmap "authenticator-config-local" to exist.
kubectl apply -f authenticator-config.yml

cd $here/authenticator/ldap
./burnup

cd $here/authenticator/postgres
./burnup

cd $here/authenticator/api
./burnup

