#!/bin/bash

here=`pwd`

echo "streams:"
cd $here/mysql
./burndown

# migrated to influx2
# this takes down older version (non-destructive)
cd $here/influx
./burndown

cd $here/influx2
./burndown

cd $here/chords
./burndown

cd $here/api
./burndown


cd $here
kubectl delete -f streams-config.yml
