#!/bin/bash

here=`pwd`

# Set up configmap for streams and kapacitor
kubectl apply -f streams-config.yml
kubectl apply -f kapacitor-config.yml

echo "streams:"
cd $here/mysql
./burnup

cd $here/influx2
./burnup

cd $here/chords
./burnup

cd $here/api
./burnup

cd $here/kapacitor
./burnup

