#!/bin/bash

echo "meta:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/meta
mkdir -p {{ tapisdatadir }}/meta/restheart-mongo

# Set up configmap 
kubectl apply -f meta-config.yml

cd $here/mongo
./burnup

cd $here/api
./burnup
