#!/bin/bash

# configs
kubectl delete -f actors-config.yml 
kubectl delete -f nginx-config.yml
kubectl delete -f prometheus-config.yml
kubectl delete -f configmap.yml

# apps
kubectl delete -f reg.yml
kubectl delete -f mes.yml
kubectl delete -f admin.yml
kubectl delete -f events.yml
kubectl delete -f prometheus.yml
kubectl delete -f grafana.yml
kubectl delete -f metrics.yml
kubectl delete -f nginx.yml

# storage
#kubectl delete -f mongo.yml
#kubectl delete -f rabbit.yml
#kubectl delete -f mongo-pvc.yml
#kubectl delete -f rabbitmq-pvc.yml
