#!/bin/bash

echo "jobs:"

here=`pwd`

# Set up configmap for jobs
kubectl delete -f jobs-config.yml

cd $here/readers
./burndown

cd $here/workers
./burndown

cd $here/api
./burndown

cd $here/rabbitmq
./burndown

cd $here/postgres_16
./burndown

cd $here