#!/bin/bash

echo "jobs:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/jobs
mkdir -p {{ tapisdatadir }}/jobs/postgres
mkdir -p {{ tapisdatadir }}/jobs/rabbitmq


# Set up configmap for jobs
cd $here
kubectl apply -f jobs-config.yml

cd $here/postgres_16
./burnup

cd $here/rabbitmq
./burnup

cd $here/api
./burnup

cd $here/workers
./burnup

cd $here/readers
./burnup

