#!/bin/bash

kubectl apply -f pvc.yml  

kubectl apply -f service.yml 
kubectl apply -f deploy.yml
kubectl wait --timeout=180s --for=condition=available deploy/tenants-postgres

kubectl apply -f migrations.yml 
kubectl wait --timeout=180s --for=condition=complete job/tenants-migrations

