#!/bin/bash

echo "security:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/security

kubectl apply -f security-kernel-config.yml

echo "security security-kernel:"
cd $here/postgres
./burnup

# vault secret renewed in here
cd $here/api
./burnup

