#!/bin/sh
#
# Do a full burnup for the Applications service
#

here=`pwd`

# Set up configmap for apps
cd $here
kubectl apply -f apps-config.yml


# Deploy postgres and api
cd $here/postgres
./burnup

cd $here/api
./burnup

