#!/bin/sh
#
# Do a full burndown for the Applications service
#


here=`pwd`


# UnDeploy api and postgres

cd $here/api
./burndown

cd $here/postgres_16
./burndown

cd $here
kubectl delete -f apps-config.yml

cd $here