#!/bin/sh
#
# Do a full burnup for the Applications service
#

here=`pwd`

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/irods

# Set up configmap for apps
cd $here
kubectl apply -f apps-config.yml


# Deploy postgres and api
cd $here/postgres_16
./burnup

cd $here/api
./burnup

cd $here
