#!/bin/bash

echo "Actung!"
echo "If you're sure you want to take it down, do stuff like this:"
echo
echo "kubectl delete -f kibana-deploy.yml"
echo "kubectl delete -f kibana-service.yml"
echo "..."

kubectl delete -f kibana-deploy.yml
kubectl delete -f elasticsearch-deploy.yml
