#!/bin/bash

# Set up configmap for jobs
kubectl apply -f ../jobs-config.yml

kubectl apply -f pvc.yml  
#kubectl wait --for=condition=complete job/mkdir-jobs-postgres-pvc
#kubectl wait --for=condition=complete job/chown-jobs-postgres-pvc
#kubectl delete job/mkdir-jobs-postgres-pvc
#kubectl delete job/chown-jobs-postgres-pvc

kubectl apply -f service.yml 

kubectl apply -f deploy.yml
kubectl apply -f pgadmin.yml 

kubectl wait --for=condition=available deploy/jobs-postgres

