kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jobs-postgres-vol02
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{jobs_storage_class}}
  resources:
    requests:
      storage: 20Gi

