apiVersion: v1
kind: Service
metadata:  
  name: jobs-postgres
spec:
  type: NodePort
  selector:    
    app: jobs-postgres
  ports:  
  - name: postgres
    port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:  
  name: jobs-pgadmin
spec:
  type: NodePort
  selector:    
    app: jobs-pgadmin
  ports:  
  - name: http
    port: 80
    targetPort: 80

