apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: tapis/notifications:{{notifications_image_version}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8000
            name: "jvm-debug"
        env:
          - name: TAPIS_DB_JDBC_URL
            value: jdbc:postgresql://notifications-postgres:5432/tapisntfdb
          - name: TAPIS_DB_USER
            value: tapis_ntf
          - name: TAPIS_SITE_ID
            valueFrom:
              configMapKeyRef:
                name: notifications-config
                key: site_id
          - name: TAPIS_TENANT_SVC_BASEURL
            valueFrom:
              configMapKeyRef:
                name: notifications-config
                key: service_site_url
          - name: TAPIS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: postgres-password
          - name: TAPIS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: service-password
          - name: TAPIS_QUEUE_HOST
            value: "notifications-rabbitmq"
          - name: TAPIS_QUEUE_ADMIN_USER
            value: "tapis"
          - name: TAPIS_QUEUE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: rabbitmq-password
          - name: TAPIS_QUEUE_USER
            value: "notif"
          - name: TAPIS_QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: rabbitmq-user-password
