#!/bin/bash

# Renew the vault secret-id token
cur=`pwd`
cd ../renew-sk-secret
./burnup
sleep 5
cd $cur

# Create a configmap of the skadmin input files in the staging directory.
kubectl create configmap sk-admin-updateload --from-file ./updateFiles

# Recreate a configmap of the command executed in the skadmin container.
kubectl delete configmap run-sk-update
kubectl create configmap run-sk-update --from-file run-sk-update

# Run the skadmin job.
kubectl delete job sk-admin-update
kubectl apply -f sk-admin-update.yml
kubectl wait --for=condition=complete job/sk-admin-update

# Clean up.
kubectl delete configmap sk-admin-updateload

