#!/bin/bash

#export KUBE_TOKEN=/var/run/secrets/kubernetes.io/serviceaccount/token
export KUBE_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`
export KUBE_NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`

echo debug100 roleid
echo $VAULT_ROLEID
echo debug110 secretid
echo $VAULT_SECRETID
echo debug120 token
echo $KUBE_TOKEN
echo debug130 namespace
echo $KUBE_NAMESPACE


#java -Djdk.tls.client.protocols=TLSv1.3 -cp /usr/local/bin/shaded-securitylib.jar edu.utexas.tacc.tapis.security.commands.SkAdmin -c -i /tmp/initialLoad -vr VAULT_ROLEID -vs VAULT_SECRETID -b {{skadmin_vault_url}} -kt KUBE_TOKEN -kn KUBE_NAMEPSACE -ku https://kubernetes.default.svc.cluster.local
java -Djdk.tls.client.protocols=TLSv1.3 -cp /usr/local/bin/shaded-securitylib.jar edu.utexas.tacc.tapis.security.commands.SkAdmin -c -i /tmp/updateLoad -vr $VAULT_ROLEID -vs $VAULT_SECRETID -b {{skadmin_vault_url}} -dm -kt KUBE_TOKEN -kn $KUBE_NAMESPACE -ku https://kubernetes.default.svc.cluster.local
