#!/bin/bash

# Set up configmap for jobs
kubectl apply -f ../jobs-config.yml

kubectl apply -f pvc.yml  

kubectl apply -f service.yml 

kubectl apply -f deploy.yml

kubectl wait --for=condition=available deploy/jobs-rabbitmq

