kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pods-nfs-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ pods_storage_class }}
  resources:
    requests:
      storage: 10Gi
