apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-traefik
spec:
  selector:
    matchLabels:
      app: pods-traefik
  template:
    metadata:
      labels:
        app: pods-traefik

    spec:
      containers:
      - name: pods-traefik
        image: {{ pods_traefik_image }}
        resources:
          requests:
            cpu: "400m"
            memory: "600M"
          limits:
            cpu: "3"
            memory: "3G"
        ports:
          - name: web
            containerPort: 80
          - name: dash
            containerPort: 8080
        args:
        ## This is used as the static Traefik config so we don't need extra files
        - --api.true
        #- --api.insecure=true
        - --api.dashboard=true

        - --accesslog=true
        - --tracing=false
        - --log.level=TRACE # TRACE | DEBUG | INFO
        
        ## Certificate resolver
        - --certificatesresolvers.tlsletsencrypt.acme.tlschallenge=true                                                                                        
        - --certificatesresolvers.tlsletsencrypt.acme.storage=/etc/traefik3/acme.json
        # To use letsencrypts staging server, to avoid rate limiting when testing
        #- --certificatesresolvers.tlsletsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        # To use zerossl rather than letsencrypt, create account, fill in eab.kid and eab.hmacencoded.
        #- --certificatesresolvers.tlsletsencrypt.acme.caserver=https://acme.zerossl.com/v2/DV90
        #- --certificatesresolvers.tlsletsencrypt.acme.email=email@domain
        #- --certificatesresolvers.tlsletsencrypt.acme.eab.kid=fromwebsite
        #- --certificatesresolvers.tlsletsencrypt.acme.eab.hmacencoded=fromwebsite

        ## Entrypoints
        - --entrypoints.web.address=:80
        - --entrypoints.web.asdefault=true
        ## timeout definitions, ensure haproxy and nginx are also >= to these values.
        - --entrypoints.web.transport.respondingtimeouts.readtimeout=3600
        - --entrypoints.web.transport.respondingtimeouts.idletimeout=3600
        - --entrypoints.web.transport.respondingtimeouts.writetimeout=3600

        ## Define providers for the dynamic config
        - --providers.http=true
        - --providers.http.endpoint=http://pods-api:8000/traefik-config
        volumeMounts:
        - name: acme-storage
          mountPath: /etc/traefik3/acme.json
          subPath: acme.json

      volumes:
      - name: acme-storage
        persistentVolumeClaim:
          claimName: pods-traefik-vol01
