kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apps-postgres-vol01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{apps_storage_class}}
  resources:
    requests:
      storage: 20Gi

