kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{systems_postgres_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{systems_storage_class}}
  resources:
    requests:
      storage: 20Gi
