kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: systems-postgres-16-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 20Gi

