apiVersion: v1
kind: Service
metadata:  
  name: systems-postgres-16
spec:
  selector:    
    app: systems-postgres-16
  ports:  
  - name: postgres
    port: 5432
    targetPort: 5432


---

apiVersion: v1
kind: Service
metadata:
  name: systems-pgadmin
spec:
  type: NodePort
  selector:
    app: systems-pgadmin
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: systems-postgres-external
spec:
  type: NodePort
  selector:
    app: systems-postgres
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
