#!/bin/bash

kubectl delete -f systems-init-db.yml
kubectl delete configmap systems-init-db-configmap

kubectl create configmap systems-init-db-configmap --from-file systems-init-db-sh
kubectl create -f systems-init-db.yml
kubectl wait --timeout=120s --for=condition=complete job/systems-init-db

