#!/bin/bash
# Script to initialize systems service DB using psql
# Create database, user and schema
# Postgres password must be set in env var POSTGRES_PASSWORD

if [ -z "$DB_HOST" ]; then
  DB_HOST=systems-postgres-16
fi

DB_USER=postgres
DB_NAME=tapissysdb

if [ -z "${POSTGRES_PASSWORD}" ]; then
  echo "Please set env var POSTGRES_PASSWORD before running this script"
  exit 1
fi

# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${POSTGRES_PASSWORD}

# Run psql command to create database if it does not exist
echo "SELECT 'CREATE DATABASE ${DB_NAME} ENCODING=\"UTF8\" LC_COLLATE=\"en_US.utf8\" LC_CTYPE=\"en_US.utf8\" ' \
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec" \
  | psql --host=${DB_HOST} --username=${DB_USER}


# Run sql to create user and schema if they do not exist
psql --host=${DB_HOST} --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE tapis_sys WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: tapis_sys';
END
\$\$;
ALTER USER tapis_sys WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE tapissysdb TO tapis_sys;

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS tapis_sys AUTHORIZATION tapis_sys;
ALTER ROLE tapis_sys SET search_path = 'tapis_sys';
EOB

# this is the password :60f0c5bf8ed23120fc60
# end

### hammock/mpackard 20210616


# Script to add Monitoring read only access for Systems service DB using psql
# user and grant read only acces
# Postgres password must be set in env var MONITOR_PASSWORD

if [ -z "${MONITOR_PASSWORD}" ]; then
  echo "Please set env var MONITOR_PASSWORD before running this script"
  exit 1
fi

# Run sql to create user if it does not exist
psql --host=${DB_HOST} --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE monitor WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: monitor';
END
\$\$;
ALTER USER monitor WITH ENCRYPTED PASSWORD '${MONITOR_PASSWORD}';
GRANT SELECT ON ALL TABLES IN SCHEMA tapis_sys TO monitor;
GRANT CONNECT ON DATABASE tapissysdb TO monitor;
GRANT USAGE ON SCHEMA tapis_sys TO monitor;

EOB
