#!/bin/bash
# Script to add Monitoring read only access for syss service DB using psql
# user and grant read only acces
# Postgres password must be set in env var MONITOR_PASSWORD

if [ -z "$DB_HOST" ]; then
  DB_HOST=sytems-postgres
fi

DB_USER=monitor
DB_NAME=tapissysdb

if [ -z "${MONITOR_PASSWORD}" ]; then
  echo "Please set env var MONITOR_PASSWORD before running this script"
  exit 1
fi

# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${MONITOR_PASSWORD}

# Run sql to create user if it does not exist
psql --host=${DB_HOST} --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE monitor WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: monitor';
END
\$\$;
ALTER USER monitor WITH ENCRYPTED PASSWORD '${MONITOR_PASSWORD}';
GRANT SELECT ON DATABASE tapissysdb TO monitor;

EOB
