---

# Ensure global vars are defined and checked

- name: Test that important variables are present and not empty
  assert:
    that:
      - tapisdir != ''
      - tapisdatadir != ''
      - components_to_deploy != ''
      - global_service_tenant_id != ''
      - global_devtenant_id != ''
      - global_service_domain != ''
      - global_primary_site_admin_tenant_base_url != ''
      - global_service_url != ''
      - global_devtenant_url != ''
      - global_vault_url != ''
      - global_auditing_enabled != ''

- name: If associate site (site_type 2), check a few variables 
  assert:
    that:
      - global_service_tenant_id != 'admin'
      - global_devtenant_id != 'dev'
      - global_tapis_domain != '{{ global_service_domain }}'
  when:
    - site_type == 2

- name: Print important vars
  ansible.builtin.debug:
    var: "{{ item }}" 
  with_items:
    - tapisdir
    - tapisdatadir
    - components_to_deploy
    - global_service_tenant_id
    - global_devtenant_id
    - global_service_domain
    - global_primary_site_admin_tenant_base_url
    - global_service_url
    - global_devtenant_url
    - global_vault_url 
    - global_auditing_enabled

# Use set_fact on global vars so the following roles can use them

- name: Set global vars
  ansible.builtin.set_fact:
    tapisdir: '{{ tapisdir }}'
    tapisdatadir: '{{ tapisdatadir }}'
    components_to_deploy: '{{ components_to_deploy }}'
    global_service_tenant_id: '{{ global_service_tenant_id }}'
    global_devtenant_id: '{{ global_devtenant_id }}'
    global_service_domain: '{{ global_service_domain }}'
    global_primary_site_admin_tenant_base_url: '{{ global_primary_site_admin_tenant_base_url }}'
    global_service_url: '{{ global_service_url }}'
    global_devtenant_url: '{{ global_devtenant_url }}'
    global_vault_url: '{{ global_vault_url }}'
    global_auditing_enabled: '{{ global_auditing_enabled }}'

