---

- name: Set default values for vars
  ansible.builtin.set_fact:
    global_service_tenant_id: '{{ global_service_tenant_id | default(global_service_tenant_id_default) }}'
    tapisdir: '{{ tapisdir | default(tapisdir_default) }}'
    tapisdatadir: '{{ tapisdatadir | default(tapisdatadir_default) }}'
    global_vault_url: '{{ global_vault_url | default(global_vault_url_default) }}'
    #global_service_url: '{{ global_service_url | default(global_service_url_default) }}'
    global_service_url: '{{ global_service_url }}'
    components_to_deploy: '{{ components_to_deploy | default(components_to_deploy_default) }}'
    #global_devtenant_url: '{{ global_devtenant_url | default(global_devtenant_url_default) }}'
    global_devtenant_url: '{{ global_devtenant_url }}'
    #global_primary_site_admin_tenant_base_url: '{{ global_primary_site_admin_tenant_base_url | default(global_primary_site_admin_tenant_base_url_default) }}'
    global_primary_site_admin_tenant_base_url: '{{ global_primary_site_admin_tenant_base_url }}'

- name: Values being used
  ansible.builtin.debug:
    msg: 
      - 'tapisdir: {{ tapisdir }}'
      - 'tapisdatadir: {{ tapisdatadir }}'
      - 'components_to_deploy: {{ components_to_deploy }}'
