#!/bin/bash

echo "burnup skadmin:"

mkdir -p {{ tapisdatadir }}/skadmin

# TODO
# check if skadmin is already done
#if true 
#then
#  echo "skadmin done. Exiting burnup."
#  exit 0
#fi

if [ "$( docker container inspect -f {% raw %}'{{.State.Running}}'{% endraw %} vault )" != "true" ]
then 
  echo "Vault container, which is required by skadmin, is not running. Exiting."
  exit 1
fi

# check if skadmin is already done
if [ -f {{ tapisdatadir }}/skadmin/env ]
then
  if [ -s {{ tapisdatadir }}/skadmin/env ]
  then
    echo "{{ tapisdatadir }}/skadmin/env is populated, so we assume skadmin is done. Skipping the rest of skadmin burnup."
    exit 0
  fi
fi

# mv skadmin env file out of the way if it is empty 
if [ -f {{ tapisdatadir }}/skadmin/env ]
then
  if [ $(wc -l < "{{ tapisdatadir }}/skadmin/env") -lt 2 ]
  then
    echo "WARN: {{ tapisdatadir }}/skadmin/env is present but empty. Moving it out of the way."
    mv {{ tapisdatadir }}/skadmin/env {{ tapisdatadir }}/skadmin/env.bak 
  fi
fi


export VAULT_TOKEN=`cat {{ tapisdatadir }}/vault/vault-token`
export SKEXPORT_PARMS="-vtok $VAULT_TOKEN -vurl {{ skadmin_vault_url }} -noskip"

# create vault roles and policies
docker run --name skadmin-presetup -it --rm --net tapis --env VAULT_TOKEN --env SKEXPORT_PARMS \
-v ./create-sk-roles:/tmp/create-sk-roles \
-v ./tapis-vault/policies/sk:/tmp/sk-policies \
-v ./tapis-vault/policies/sk-admin:/tmp/sk-admin-policies \
-v ./tapis-vault/roles:/tmp/sk-roles \
{{ skadmin_util_image }} /tmp/create-sk-roles

export VAULT_SECRETID=`docker run --name skadmin-presetup -it --rm --net tapis --env VAULT_TOKEN \
{{ skadmin_util_image }} curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/auth/approle/role/sk/secret-id | jq -r .data.secret_id`

export VAULT_ROLEID=`docker run --name skadmin-presetup -it --rm --net tapis --env VAULT_TOKEN \
{{ skadmin_util_image }} curl -s -X GET -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/auth/approle/role/sk/role-id | jq -r .data.role_id`

if [ -z "$VAULT_SECRETID" ]
then
  echo "\$VAULT_SECRETID is empty. Exiting."
  exit 1
fi

if [ -z "$VAULT_ROLEID" ]
then
  echo "\$VAULT_ROLEID is empty. Exiting."
  exit 1
fi

# create tapis passwords in vault
docker run --name skadmin-init -it --rm --net tapis --env VAULT_ROLEID --env VAULT_SECRETID \
-v ./initialLoad:/tmp/initialLoad \
-v ./run-sk-admin:/tmp/run-sk-admin \
{{ skadmin_securityadmin_image }} /tmp/run-sk-admin

# export tapis passwords to env file
docker run --name skadmin-export -it --rm --net tapis --env SKEXPORT_PARMS {{ skadmin_securityexport_image }} > {{ tapisdatadir }}/skadmin/env

{% if site_type == 2 %}
echo "Collecting public keys for associate site tenants. Please send these to your tenants admin before next steps in deployment."
cd ../admin
./get-assocsite-publickeys
{% endif %}

