#!/bin/bash

echo "burnup tapisui:"

# mkdir -p {{ tapisdatadir }}/tapisui
# MYUID=`id -u`
# docker run -it --rm -v {{ tapisdatadir }}/tapisui:/tapisui tapis/ubutil2204:1.4.0 chown $MYUID /tapisui

# python3 ../admin/util/parse_skexport -c tapisui -d {{ tapisdatadir }}

docker compose up -d
