#!/bin/bash

for i in `kubectl get secret tapis-tokens-secrets  -o jsonpath="{.data}" | jq -r 'keys[]'`
do
  echo ---
  echo $i
  kubectl get secret tapis-tokens-secrets  -o jsonpath="{.data.$i}" | base64 -d > /tmp/pktmp
  chmod 600 /tmp/pktmp
  ssh-keygen -y -f /tmp/pktmp
  rm -f /tmp/pktmp
done

