#!/bin/bash

kubectl apply -f tokens-config.yml
kubectl apply -f service.yml
kubectl apply -f api.yml 

# kubectl apply -f add-token-roles.yml
# kubectl wait --for=condition=complete job/add-token-roles

