#!/bin/bash

set -e

here=`pwd`
nfsServerIp=$(kubectl get service mlhub-nfs-server-service -o jsonpath='{.spec.clusterIP}')
echo got nfs server IP: $nfsServerIp
nfsServerIpTemplate="\*\* NFS_SERVER_COMPONENT_IP \*\*"

sed -i.bak "s|${nfsServerIpTemplate}|${nfsServerIp}|g" "$here/deployment.yml"
rm "$here/deployment.yml.bak"

kubectl apply -f "$here/service.yml" \
    -f "$here/deployment.yml"
