apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-models-api-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-models-api-deployment
  template:
    metadata:
      labels:
        app: mlhub-models-api-deployment
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mlhub-postgres-service
            - name: DB_NAME
              value: mlhub
            - name: DB_PASSWORD
              value: dev
            - name: DB_USER
              value: mlhub
            - name: RUST_LOG
              value: debug
            - name: SHARED_DATA
              value: /srv/mlhub
          image: {{ mlhub_models_api_image }}
          imagePullPolicy: Always
          name: mlhub-models-api
          ports:
            - containerPort: 8000
              name: webserver
          # readinessProbe:
          #   httpGet:
          #     path: /models-api/health-check
          #     port: 8000
          #   initialDelaySeconds: 2
          #   periodSeconds: 15
          #   failureThreshold: 5
          resources: {}
          tty: true
          volumeMounts:
              - name: nfs-server-mount
                mountPath: /srv/mlhub/
      volumes:
        - name: nfs-server-mount
          nfs:
            server: '** NFS_SERVER_COMPONENT_IP **'
            path: /
