#!/bin/sh
#
# Cleanup old postgres service resources
#

here=`pwd`

kubectl delete -f $here/apps-init-db_old.yml
kubectl delete configmap apps-init-db-configmap
kubectl delete -f $here/deploy_old.yml
