kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tenants-postgres-vol01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-new
  resources:
    requests:
      storage: 20Gi
