#!/bin/bash

echo "burnup actors:"

mkdir -p {{ tapisdatadir }}/actors
MYUID=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/actors:/actors {{ actors_util_image }} chown $MYUID /actors

python3 ../admin/util/parse_skexport -c actors -d {{ tapisdatadir }}

docker compose up -d
