#!/bin/bash

echo "burnup actors:"

mkdir -p {{ tapisdatadir }}/actors
myuid=`id -u`
docker run -it --rm -v {{ tapisdatadir }}/actors:/actors tapis/ubutil2204:1.4.0 chown $myuid /actors

python3 {{ tapisdir }}/admin/util/parse_skexport -c actors -d {{ tapisdatadir }}

docker-compose up -d
