#!/bin/sh
#
# Cleanup old postgres service resources
#

here=`pwd`

kubectl delete -f $here/systems-init-db_old.yml
kubectl delete configmap systems-init-db-configmap
kubectl delete -f $here/deploy_old.yml
