#!/bin/bash

here=`pwd`

cd $here/traefik
./burndown

cd $here/nfs
./burndown

cd $here/mongo
./burndown

cd $here/rabbit
./burndown

cd $here/artifact-ingester
./burndown

cd $here/artifact-publisher
./burndown

cd $here/models
./burndown