apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-api
spec:
  selector:
    matchLabels:
      app: sk-api
  template:
    metadata:
      labels:
        app: sk-api
    spec:
{% if security_renew_sk_script == true %}
{% if skadmin_sk_privileged_sa is not none %}
      serviceAccountName: {{ skadmin_sk_privileged_sa }}
{% endif %}
      initContainers:
      - name: renew-sk-secret
        command: ["/tmp/renew-sk-secret-script"]
        #command: ["sleep","3600"]
        image: {{ security_skadminutil_image }}
        imagePullPolicy: {{security_image_pull_policy}}
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        volumeMounts:
        - name: renew-sk-secret
          mountPath: /tmp/renew-sk-secret-script
          subPath: renew-sk-secret-script
{% endif %}
      containers:
      - name: sk-api
        image: {{ security_api_image }}
        imagePullPolicy: {{security_image_pull_policy}}
        ports:
        - name: tomcat1
          containerPort: 8000
        - name: tomcat2
          containerPort: 8080
        - name: tomcat3
          containerPort: 8443
        - name: debug
          containerPort: 6157
        env:
        - name: TAPIS_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: security-kernel-config
              key: site_id
        - name: TAPIS_TENANT_SVC_BASEURL
          valueFrom:
            configMapKeyRef:
              name: security-kernel-config
              key: service_site_url
        - name: TAPIS_SK_VAULT_DISABLE
          value: "false"
        - name: TAPIS_SK_VAULT_ADDRESS
          value: "{{security_vault_url}}"
        - name: TAPIS_SK_VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-secretid
        - name: TAPIS_SK_VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-roleid
        - name: TAPIS_DB_CONNECTION_POOL_SIZE
          value: "10"
        - name: TAPIS_DB_USER
          value: "tapis"
        - name: TAPIS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-sk-secrets
              key: tapis-postgres-password
        - name: TAPIS_DB_JDBC_URL
          value: "jdbc:postgresql://sk-postgres:5432/tapissecdb"
        - name: TAPIS_REQUEST_LOGGING_FILTER_PREFIXES
          value: "/v3/security"
        - name: TAPIS_REQUEST_LOGGING_IGNORE_SUFFIXES
          value: "/healthcheck;/ready;/hello"
#        - name: TAPIS_LOG_DIRECTORY
#          value: "/opt/tomcat/logs"
        - name: CATALINA_OPTS 
          value: "-Xms{{security_heap_min}} -Xmx{{security_heap_max}} --add-opens java.base/java.time=ALL-UNNAMED"
{% if security_volumes %}
      volumes:
      - name: renew-sk-secret
        configMap:
          name: renew-sk-secret
          defaultMode: 0777
{% endif %}
