#!/bin/bash

# Migrate the db and start the service.
kubectl apply -f ../security-kernel-config.yml
kubectl wait --for=condition=available deploy/sk-postgres
kubectl apply -f migrate.yml 
kubectl wait --for=condition=complete job/sk-migrate
kubectl apply -f service.yml 

{% if global_vault_url == "http://vault:8200" %}

# internal vault

{% else %}

# external vault
# Start the SK service.
../../skadmin/external-vault/reset-approle-ids

{% endif %}

kubectl apply -f api.yml 
kubectl wait --for=condition=available deploy/sk-api
