apiVersion: apps/v1
kind: Deployment
metadata:
  name: systems-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systems-api
  template:
    metadata:
      labels:
        app: systems-api
    spec:
{% if systems_node_selector is not none %}
      nodeSelector:
        exempt: "yes"
{% endif %}
      containers:
      - name: systems-api
        image: {{ systems_api_image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8000
            name: "jvm-debug"
        env:
          - name: TAPIS_DB_JDBC_URL
            value: jdbc:postgresql://systems-postgres-16:5432/tapissysdb
          - name: TAPIS_DB_USER
            value: tapis_sys
          - name: TAPIS_SITE_ID
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: site_id
          - name: TAPIS_TENANT_SVC_BASEURL
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: service_site_url
{% if systems_globus_client_id is not none %}
          - name: TAPIS_GLOBUS_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: globus_client_id
{% endif %}
          - name: TAPIS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-systems-secrets
                key: postgres-password
          - name: TAPIS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-systems-secrets
                key: service-password
{% if systems_tms_enabled is not none %}
          - name: TAPIS_TMS_ENABLED
            value: "{{ systems_tms_enabled }}"
          - name: TAPIS_TMS_SERVER_URL
            value: {{ systems_tms_server_url }}
          - name: TAPIS_TMS_TENANT
            value: {{ systems_tms_tenant }}
          - name: TAPIS_TMS_CLIENT_ID
            value: {{ systems_tms_client_id }}
          - name: TAPIS_TMS_ALLOWED_TENANTS
            value: {{ systems_tms_allowed_tenants }}
          - name: TAPIS_TMS_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: tapis-systems-secrets
                key: tms-client-key
{% endif %}
