resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: mlhub-hpc-cluster-seeder
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mlhub-hpc-cluster-seeder
      spec:
        template:
          spec:
            containers:
              - name: hpc-cluster-seeder
                image: tapis/mlhub-hpc-cluster-seeder:staging
                imagePullPolicy: Always
                resources: {}
                env:
                  - name: MONGO_HOST
                    value: mlhub-mongo-stateful-set-0.mlhub-mongo-headless-service.tapisstage.svc.cluster.local
