#!/bin/bash

kubectl apply -f ../security-kernel-config.yml
kubectl apply -f pvc-postgres.yml
kubectl apply -f service.yml
kubectl apply -f deploy.yml
kubectl apply -f pgadmin.yml

kubectl wait --timeout=180s --for=condition=available deploy/sk-postgres-16