apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-postgres-16
spec:
  selector:
    matchLabels:
      app: sk-postgres-16
  template:
    metadata:
      labels:
        app: sk-postgres-16
    spec:
      containers:
      - name: sk-postgres-16
        image: postgres:16
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: PGDATA
          value: "/pgdata/data"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-sk-secrets
              key: postgres-password
        volumeMounts:
        - name: sk-pg-data
          mountPath: "/pgdata"
      volumes:
      - name: sk-pg-data
        persistentVolumeClaim:
          claimName: sk-postgres-16-vol
