#!/bin/bash

echo "files:"

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/rabbitmq
mkdir -p {{ tapisdatadir }}/files/postgres
mkdir -p {{ tapisdatadir }}/files/minio
mkdir -p {{ tapisdatadir }}/files/irods

kubectl apply -f configmap.yml
kubectl apply -f files-config.yml

pushd ./postgres
./burnup
popd

pushd ./pgadmin
./burnup
popd

pushd ./rabbitmq
./burnup
popd

pushd ./api
./burnup
popd

pushd ./worker
./burnup
popd
