#!/bin/bash

echo "files:"

pushd ./worker
./burndown
popd

pushd ./api
./burndown
popd

pushd ./rabbitmq
./burndown
popd

pushd ./pgadmin
./burndown
popd

pushd ./postgres
./burndown
popd

kubectl delete -f files-config.yml
kubectl delete -f configmap.yml
