#!/bin/bash

echo "files:"

pushd ./assigner
./burdown
popd

pushd ./worker
./burndown
popd

pushd ./api
./burndown
popd

pushd ./rabbitmq
./burndown
popd

pushd ./pgadmin
./burndown
popd

# this burndown is used only for the upgrade.  Will be removed in a future version
pushd ./postgres
./burndown
popd

pushd ./postgres_16
./burndown
popd

kubectl delete -f files-config.yml
kubectl delete -f configmap.yml
