#!/bin/bash

echo "files:"

here=`pwd`

cd ${here}/assigner
./burndown

cd ${here}/worker
./burndown

cd ${here}/api
./burndown

cd ${here}/pgadmin
./burndown

cd ${here}/postgres_16
./burndown

cd ${here}

kubectl delete -f files-config.yml
kubectl delete -f configmap.yml
