#!/bin/bash

echo "files:"

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/rabbitmq
mkdir -p {{ tapisdatadir }}/files/postgres_16
mkdir -p {{ tapisdatadir }}/files/minio
mkdir -p {{ tapisdatadir }}/files/irods

kubectl apply -f configmap.yml

here=`pwd`

cd ${here}/postgres_16
./burnup


cd ${here}/api
./burnup

cd ${here}/assigner
./burnup

cd ${here}/worker
./burnup

cd ${here}
