#!/bin/bash

echo "monitoring:"

mkdir -p {{ tapisdatadir }}/monitoring/prometheus
mkdir -p {{ tapisdatadir }}/monitoring/grafana
mkdir -p {{ tapisdatadir }}/monitoring/elasticsearch

# kube config so we can access kube api
kubectl create configmap kubeconfig --from-file=$HOME/.kube/config

# Set up configmap for monitoring
kubectl apply -f monitoring-config.yml

# Persistent storage
kubectl apply -f pvc

# Configs
kubectl apply -f secrets.yml 

# Services
kubectl apply -f services

# Apps
kubectl apply -f apps

# Logging
kubectl apply -f stern-fluentd

# Initialize the DB
kubectl create configmap monitor-init-user-configmap --from-file monitor-init-user-sh
kubectl apply -f monitor-init-user.yml
kubectl wait --timeout=120s --for=condition=complete job/monitor-init-user
