#!/bin/bash

echo "monitoring:"

# DO NOT burn Persistent storage
# DO NOT burn Services 

# Configs
kubectl apply -f secrets.yml 
kubectl delete -f monitoring-config.yml

# Apps
kubectl delete -f apps
kubectl delete -f stern-fluentd

#Jobs
kubectl delete -f monitor-init-user.yml

# 1.6.3 Removed elasticsearch & kibana from install. Putting these here to shut down existing.
kubectl delete deploy/monitoring-elasticsearch
kubectl delete deploy/monitoring-kibana
