#!/bin/bash

echo "debug100"

#Enable V2 Key/Value Secrets
#curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/mounts/secret -d '{"type": "kv-v2"}' | /usr/bin/jq
curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/mounts/secret -d '{"type": "kv-v2"}' 

echo "debug110"
#Check the mounts:
#curl -s -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/mounts | /usr/bin/jq
curl -s -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/mounts 

echo "debug120"
#Enable Approle Authentication
#curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth/approle -d '{"type": "approle"}' | /usr/bin/jq
curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth/approle -d '{"type": "approle"}' 

echo "debug130"
#Check authenticators:
#curl -s -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth | /usr/bin/jq
curl -s -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth 

echo "debug140"
#Enable userpass authentication
#curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth/userpass -d '{"type": "userpass"}' | /usr/bin/jq
curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/sys/auth/userpass -d '{"type": "userpass"}'

#This engine is not currently used by Tapis but we still enable it.
