kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sk-postgres-vol02
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{security_storage_class}}
  resources:
    requests:
      storage: 20Gi

