#!/bin/bash

echo "streams:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/streams
mkdir -p {{ tapisdatadir }}/streams/influx
mkdir -p {{ tapisdatadir }}/streams/mysql

# config
kubectl apply -f streams-config.yml

cd $here/mysql
./burnup

cd $here/influx2
./burnup

cd $here/chords
./burnup

cd $here/api
./burnup



