#!/bin/bash

echo burnup mlhub

mkdir -p {{ tapisdatadir }}/mlhub

export MYUID="$(id -u)"
export UID_GID="$(id -u):$(id -g)"

docker run -it --rm -v {{ tapisdatadir }}/mlhub:/mlhub {{ mlhub_util_image }} chown $MYUID /mlhub

# python3 ../admin/util/parse_skexport -c mlhub -d {{ tapisdatadir }}

docker compose up -d
