networks:
  tapis:
    name: tapis
    external: true

services:
  ml-hub:
    # image: tapis/models-api:dev
    image: {{ ml_hub_models_api_image }}
    networks:
      - tapis
    container_name: ml-hub
    environment:
      - ENV=dev
      - API_PORT=5001
      - JUPYTER_PORT=8881
    volumes:
      # - ./hub:/home/tapis        # for live debugging w/ Jupyter
      - ./ml-hub-config.json:/home/tapis/config.json

  ml-hub-inference:
    # image: tapis/inference-api:dev
    image: {{ ml_hub_inference_api_image }}
    networks:
      - tapis
    container_name: ml-hub-inference
    environment:
      - ENV=dev
      - API_PORT=5002
      - JUPYTER_PORT=8882
    volumes:
      - {{ tapisdatadir }}/mlhub/inference/cache:/root/.cache    # for caching models
      # - ./inference:/home/tapis  # for live debugging w/ Jupyter
      - ./ml-hub-config.json:/home/tapis/config.json
