networks:
  tapis:
    name: tapis
    external: true

services:
  mlhub:
    # image: tapis/models-api:dev
    image: {{ mlhub_models_api_image }}
    networks:
      - tapis
    container_name: mlhub
    environment:
      - ENV=dev
      - API_PORT=5001
      - JUPYTER_PORT=8881
    volumes:
      # - ./hub:/home/tapis        # for live debugging w/ Jupyter
      - ./mlhub-config.json:/home/tapis/config.json

  mlhub-inference:
    # image: tapis/inference-api:dev
    image: {{ mlhub_inference_api_image }}
    networks:
      - tapis
    container_name: mlhub-inference
    environment:
      - ENV=dev
      - API_PORT=5002
      - JUPYTER_PORT=8882
    volumes:
      - {{ tapisdatadir }}/mlhub/inference/cache:/root/.cache    # for caching models
      # - ./inference:/home/tapis  # for live debugging w/ Jupyter
      - ./mlhub-config.json:/home/tapis/config.json
