#!/bin/bash

here=`pwd`

cd $here/api
./burndown

cd $here/engine
./burndown

cd $here/engine-streams
./burndown

cd $here/nfs-server
./burndown

cd $here/mysql
./burndown

cd $here/rabbitmq
./burndown

