resources:
  - ../../base

configMapGenerator:
- name: mlhub-cm-mongo-init-script
  behavior: replace
  files:
  - init-db.sh

patches:
  - target:
      version: v1
      kind: StatefulSet
      name: mlhub-mongo-stateful-set
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: "cinder-csi"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 50Gi