#!/bin/bash

source functions
gettoken

echo "hello"
curl -s {{ admin_devtenant_url }}/v3/security/hello
echo

echo "ready"
curl -s {{ admin_devtenant_url }}/v3/security/ready 
echo

echo "healthcheck"
curl -s {{ admin_devtenant_url }}/v3/security/healthcheck 
echo
