---
# Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana
  labels:
    app: monitoring-grafana
spec:
  selector:
    matchLabels:
      app: monitoring-grafana
  template:
    metadata:
      labels:
        app: monitoring-grafana
    spec:
      restartPolicy: Always
      initContainers:
      - name: chown-datadir
        image: alpine:3.6
        command:
        - chown
        - -R
        - 472:472
        - /var/lib/grafana
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      containers:
      - name: monitoring-grafana
        image: grafana/grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-monitoring-secrets
              key:  grafana-password
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
#        - name: GF_SERVER_DOMAIN
#          value: "dev.develop.tapis.io"
        - name: GF_SERVER_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: tenant_domain
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_AUTH_LDAP_ENABLED
          value: "true"
        - name: GF_AUTH_LDAP_CONFIG_FILE
          value: "/etc/grafana/ldap.toml"
        - name: GF_AUTH_LDAP_ALLOW_SIGN_UP
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel"
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
          subPath: grafana-datasources.yaml
          #readOnly: false
        - name: grafana-ldap
          mountPath: /etc/grafana/ldap.toml
          subPath: grafana-ldap.toml
          # readOnly: false
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-vol01
      - name: grafana-datasources
        configMap:
          name: global-config
      - name: grafana-ldap
        configMap:
          name: global-config
