#!/bin/bash

# Set up configmap for streams and kapacitor
kubectl apply -f ../streams-config.yml
kubectl apply -f ../kapacitor-config.yml

kubectl apply -f pvc.yml
kubectl wait --for=condition=complete job/chown-streams-mysql-pvc
kubectl apply -f deploy.yml
kubectl apply -f service.yml 
