#!/bin/bash

# Setup the PVC for postgres
kubectl apply -f pvc-postgres.yml

# Start postgres and pgadmin services.
# This establishes any externally accessible ports. E.g. pgadmin ClusterIP service.
# Typically services are not removed during burndown so the ports will remain the same.
kubectl apply -f service.yml

# Start postgres pod
kubectl apply -f deploy.yml

# Start pgadmin pod
kubectl apply -f pgadmin.yml

# Wait for postgres to finish coming up
kubectl wait --timeout=120s --for=condition=available deploy/notifications-postgres-16

# Initialize the DB
# First, remove any artifacts from a previous run
kubectl delete -f notifications-init-db.yml
kubectl delete configmap notifications-init-db-configmap
# Run the init script
kubectl create configmap notifications-init-db-configmap --from-file notifications-init-db-sh
kubectl create -f notifications-init-db.yml
kubectl wait --timeout=120s --for=condition=complete job/notifications-init-db
