#!/bin/sh
#
# Do a full burnup for the Notifications service
#

echo "notifications:"

mkdir -p {{ tapisdatadir }}/notifications

here=`pwd`

cd $here
kubectl apply -f notifications-config.yml

# Deploy postgres and api

cd $here/postgres_16
./burnup

cd $here/rabbitmq
./burnup

cd $here/dispatcher
./burnup

cd $here/api
./burnup
