#!/bin/bash

echo "burnup meta:"

mkdir -p {{ tapisdatadir }}/meta/restheart-mongo

myuid=`id -u`
export UID=`id -u`
export GID=`id -g`
docker run -it --rm -v {{ tapisdatadir }}/meta:/meta tapis/ubutil2204:1.3.0 chown $myuid /meta

python3 {{ tapisdir }}/admin/util/parse_skexport -c meta -d {{ tapisdatadir }}

docker compose up -d

