resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: mlhub-principals-migrator
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mlhub-principals-migrator
      spec:
        template:
          spec:
            containers:
              - image: tapis/mlhub-principals-migrator:local
                imagePullPolicy: Never
                name: principals-migrator
                resources: {}

