#!/bin/bash

# pvc
kubectl apply -f mongo-pvc.yml
kubectl wait --for=condition=complete job/chown-actors-mongo-pvc
kubectl apply -f rabbitmq-pvc.yml
kubectl wait --for=condition=complete job/chown-actors-rabbitmq-pvc

# config files
kubectl apply -f actors-config.yml
kubectl apply -f nginx-config.yml
kubectl apply -f prometheus-config.yml
kubectl apply -f configmap.yml

# services files
kubectl apply -f services.yml 

# deploy
kubectl apply -f rabbit.yml
kubectl apply -f nginx.yml
kubectl apply -f mongo.yml
kubectl apply -f reg.yml
kubectl apply -f mes.yml
kubectl apply -f admin.yml
kubectl apply -f events.yml 
kubectl apply -f prometheus.yml
kubectl apply -f grafana.yml
kubectl apply -f metrics.yml


# spawner & health & events should be on compute node?
# kubectl apply -f spawner.yml
# kubectl apply -f health.yml
# kubectl apply -f events.yml

# deprecated?
#kubectl apply -f clientg.yml
