#!/bin/bash

#events=`kubectl get service -o json actors-events  | jq -r '.spec.ports[]["nodePort"]'`
rabbit=`kubectl get service -o json actors-rabbit | jq -r '.spec.ports[0]["nodePort"]'`	
mongo=`kubectl get service -o json actors-mongo | jq -r '.spec.ports[0]["nodePort"]'`	
nginx=`kubectl get service -o json actors-nginx | jq -r '.spec.ports[0]["nodePort"]'`	
#reg=`kubectl get service -o json actors-reg | jq -r '.spec.ports[0]["nodePort"]'`	

#echo events
#echo 172.16.120.9:$events

echo rabbit
echo 172.16.120.9:$rabbit

echo mongo
echo 172.16.120.9:$mongo

echo nginx
echo 172.16.120.9:$nginx

#echo reg
#echo 172.16.120.9:$reg



