#!/bin/bash


rhpass=`kubectl get secret tapis-meta-secrets -o jsonpath='{.data.alt-mongo-password}' | base64 -d`
# need to convert / and other wily characters to url encoded
rhtmp=`python3 -c "import sys, urllib.parse as ul; print (ul.quote_plus(sys.argv[1]))" $rhpass`
kubectl delete secret restheart-security-alt-mongo-uri 
kubectl create secret generic restheart-security-alt-mongo-uri --from-literal=restheart-security-alt-mongo-uri="mongodb://restheart:${rhtmp}@restheart-mongo-vdj:27017/?authSource=admin"

#echo `k get secret tapis-meta-secrets -o jsonpath='{.data.mongo-password}'` | base64 -d 

kubectl apply -f restheart-vdj.yml 
kubectl apply -f restheart-security-vdj.yml 
kubectl apply -f service.yml
