#!/bin/bash

echo "proxy:"

here=`pwd`

mkdir -p {{ tapisdatadir }}/proxy
mkdir -p {{ tapisdatadir }}/proxy/proxy-site-router-redis

kubectl apply -f proxy-config.yml

echo "proxy nginx:"
cd $here/nginx
./burnup

echo "proxy site-router:"
cd $here/site-router
./burnup

