apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
spec:
  selector:
    matchLabels:
      app: jobs-api
  template:
    metadata:
      labels:
        app: jobs-api
    spec:
      initContainers:
      automountServiceAccountToken: false
{% if jobs_node_selector is not none %}
      nodeSelector:
        exempt: "yes"
{% endif %}
      containers:
      - name: jobs-api
        image: {{ jobs_api_image }}
        imagePullPolicy: Always
        ports:
        - name: tomcat1
          containerPort: 8000
        - name: tomcat2
          containerPort: 8080
        - name: tomcat3
          containerPort: 8443
        - name: debug
          containerPort: 6157
        env:
{% if jobs_node_name == true %}
        - name: TAPIS_LOCAL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{% endif %}
        - name: TAPIS_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: site_id
        - name: TAPIS_TENANT_SVC_BASEURL
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: service_site_url
        - name: TAPIS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: service-password
        - name: TAPIS_DB_CONNECTION_POOL_SIZE
          value: "10"
        - name: TAPIS_DB_USER
          value: "tapis"
        - name: TAPIS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: tapis-postgres-password
        - name: TAPIS_DB_JDBC_URL
          value: "jdbc:postgresql://jobs-postgres-16:5432/tapisjobsdb"
        - name: TAPIS_QUEUE_HOST
          value: jobs-rabbitmq
        - name: TAPIS_QUEUE_ADMIN_USER
          value: "tapis"
        - name: TAPIS_QUEUE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-tapis-password
        - name: TAPIS_QUEUE_USER
          value: "jobs"
        - name: TAPIS_QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-jobs-password
        - name: TAPIS_REQUEST_LOGGING_FILTER_PREFIXES
          value: "/v3/jobs"
        - name: TAPIS_REQUEST_LOGGING_INGORE_SUFFIXES
          value: "/healthcheck;/ready;/hello"
        - name: TAPIS_AUDITING_ENABLED
          value: "{{ global_auditing_enabled }}"
#        - name: TAPIS_LOG_DIRECTORY
#          value: "/opt/tomcat/logs"
        - name: CATALINA_OPTS 
          value: "-Xms1g -Xmx3g --add-opens java.base/java.time=ALL-UNNAMED"
