resources:
  - ../../base
  - ../../../site-configs/overlays/tapisprod
patches:
  - target:
      kind: Deployment
      name: mlhub-artifact-ingester-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mlhub-artifact-ingester-deployment
      spec:
        template:
          spec:
            containers:
              - name: artifact-ingester
                image: tapis/mlhub-artifact-ingester:26Q1
                imagePullPolicy: Always
                resources: {}
