---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pg-16-data
  name: files-pg-16-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-new
  resources:
    requests:
      storage: 10G
