#!/bin/bash

# This program uses the Tapis administrative vault token to delete and reassign
# the AppRole role-id and secret-id, the latter of which is has a ttl of 10 
# minutes.  These values are stored in a Kubernetes secret and injected into
# the SK container when it starts.  SK uses these secrets to obtain its 
# initial AppRole token.

if [ ! -f {{ tapisdatadir }}/vault/vault-token ]
then
  echo "boo. need to create {{ tapisdatadir }}/vault/vault-token"
  exit 1
fi

# Put the Tapis administrative vault token into a local variable.
VAULT_TOKEN=`cat {{ tapisdatadir }}/vault/vault-token`

# Get a fresh pair of approle ids.
kubectl delete secret tapis-sk-vault-secrets
kubectl create secret generic tapis-sk-vault-secrets --from-literal=vault-secretid=`curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" {{skadmin_vault_url}}/v1/auth/approle/role/sk/secret-id | jq -r .data.secret_id` --from-literal=vault-roleid=`curl -s -X GET -H "X-Vault-Token: $VAULT_TOKEN" {{skadmin_vault_url}}/v1/auth/approle/role/sk/role-id | jq -r .data.role_id`

