#!/bin/bash

echo "burnup files:"

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/rabbitmq
mkdir -p {{ tapisdatadir }}/files/postgres
mkdir -p {{ tapisdatadir }}/files/minio
mkdir -p {{ tapisdatadir }}/files/irods

myuid=`id -u`
export UID=`id -u`
export GID=`id -g`
docker run -it --rm -v {{ tapisdatadir }}/files:/files tapis/ubutil2204:1.4.0 chown $myuid /files

python3 {{ tapisdir }}/admin/util/parse_skexport -c files -d {{ tapisdatadir }}

docker compose up -d

