#!/bin/bash

echo "burnup files:"

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/rabbitmq
mkdir -p {{ tapisdatadir }}/files/postgres
mkdir -p {{ tapisdatadir }}/files/minio
mkdir -p {{ tapisdatadir }}/files/irods

MYUID=`id -u`

export UID_GID="$(id -u):$(id -g)"

docker run -it --rm -v {{ tapisdatadir }}/files:/files tapis/ubutil2204:1.4.0 chown $MYUID /files

python3 ../admin/util/parse_skexport -c files -d {{ tapisdatadir }}

docker compose up -d

