#!/bin/bash

echo "burnup files:"

mkdir -p {{ tapisdatadir }}/files
mkdir -p {{ tapisdatadir }}/files/rabbitmq
mkdir -p {{ tapisdatadir }}/files/postgres
mkdir -p {{ tapisdatadir }}/files/minio
mkdir -p {{ tapisdatadir }}/files/irods

python3 ../admin/util/parse_skexport -c files -d {{ tapisdatadir }}

docker compose up -d

