resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: mlhub-federated-identities-migrator
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mlhub-federated-identities-migrator
      spec:
        template:
          spec:
            containers:
              - name: federated-identities-migrator
                image: tapis/mlhub-federated-identities-migrator:staging
                imagePullPolicy: Always
                resources: {}
                env:
                  - name: MONGO_HOST
                    value: mlhub-mongo-stateful-set-0.mlhub-mongo-headless-service.tapisstage.svc.cluster.local

