#!/bin/bash

echo "pgrest:"

mkdir -p {{ tapisdatadir }}/pgrest

# Config
kubectl apply -f pgrest-config.yml

# Services
kubectl apply -f pgrest-service.yml
kubectl apply -f api-service.yml

# PVC
kubectl apply -f postgres-pvc.yml

# Deploy
kubectl apply -f postgres-deploy.yml
kubectl apply -f api-deploy.yml
