#!/bin/bash

# Delete current kube secrets and re-populate with data from vault
#
# Useful during a Tapis upgrade, not recommended during a Tapis installation burnup.

if [ "$1" == "--yes" ]
then

  set -e

  echo "skadmin update kube passwords:"

  here=`pwd`

  # renew short-term sk vault secret
  ./external-vault/reset-approle-ids

  kubectl delete configmap sk-admin-initialload
  kubectl create configmap sk-admin-initialload --from-file ${here}/initialLoad

  kubectl delete configmap run-sk-admin
  kubectl create configmap run-sk-admin --from-file run-sk-admin

  kubectl delete job sk-admin-init
  kubectl apply -f sk-admin-init.yml
  kubectl wait --for=condition=complete job/sk-admin-init

else

  echo "This will delete your kube secrets and replace with data from vault."
  echo "Run with --yes if you really want to do this."

fi


