#!/usr/bin/env python

import yaml
import sys

ymlfile = sys.argv[1]

with open(ymlfile, 'r') as file:
  docs = yaml.safe_load_all(file)
  try: 
    for doc in docs:
      pass
  except Exception as e: 
    print('ERROR: Problem validating some YAML in file {}').format(ymlfile)
    sys.exit(1)

sys.exit(0)
