#!/bin/bash

kubectl apply -f service.yml 
kubectl apply -f pvc.yml 
kubectl apply -f deploy.yml 
kubectl wait --for=condition=available deploy/files-postgres

# Initialize the db
kubectl create configmap files-init-db-configmap --from-file files-init-db-sh
kubectl create -f files-init-db.yml
kubectl wait --timeout=120s --for=condition=complete job/files-init-db
