#!/bin/bash

echo "burnup jobs:"

mkdir -p {{ tapisdatadir }}/jobs
mkdir -p {{ tapisdatadir }}/jobs/postgres_16

python3 ../admin/util/parse_skexport -c jobs -d {{ tapisdatadir }}

docker compose up -d

