#!/bin/bash

#set -e

here=`pwd`

kubectl apply -f "$here/traefik-dynamic-config.yaml" 
kubectl apply -f "$here/deployment.yaml" 
kubectl apply -f "$here/web-service.yaml" 
kubectl apply -f "$here/dashboard-service.yaml"
