apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
data:
  dynamic-config.yaml: |-
    http:
      routers:
        dashboard:
          rule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
          service: api@internal

        models-api:
          rule: "PathPrefix(`/v3/mlhub/models`)"
          service: models-api
        
        datasets-api:
          rule: "PathPrefix(`/v3/mlhub/datasets`)"
          service: datasets-api

        inference-api:
          rule: "PathPrefix(`/v3/mlhub/inference`)"
          service: inference-api

        training-api:
          rule: "PathPrefix(`/v3/mlhub/training`)"
          service: training-api

      services:
        models-api:
          loadBalancer:
            servers:
            - url: http://models-api-service:8000
        datasets-api:
          loadBalancer:
            servers:
            - url: http://datasets-api-service:8000
        inference-api:
          loadBalancer:
            servers:
            - url: http://inference-api-service:8000
        training-api:
          loadBalancer:
            servers:
            - url: http://training-api-service:8000









