apiVersion: v1
kind: Service
metadata:
  name: mlhub-web-traefik-service
  # selector:
  #   app: mlhub-web-traefik-deployment

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik