#!/bin/bash

echo "burnup authenticator:"

python3 {{ tapisdir }}/admin/util/parse_skexport -c authenticator -d {{ tapisdatadir }}

# docker run --name authenticator-migrations -it --rm --net tapis --env-file {{ tapisdatadir }}/authenticator/env {{ authenticator_migrations_image }} upgrade

docker compose up -d

