apiVersion: apps/v1
kind: Deployment
metadata:
  name: systems-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systems-api
  template:
    metadata:
      labels:
        app: systems-api
    spec:
      {%- if systems_node_selector | default(None) %}
      nodeSelector:
        exempt: "{{systems_node_selector}}"
      {%- endif%}
      containers:
      - name: systems-api
        image: tapis/systems:{{systems_image_version}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8000
            name: "jvm-debug"
        env:
          - name: TAPIS_DB_JDBC_URL
            value: jdbc:postgresql://systems-postgres:5432/tapissysdb
          - name: TAPIS_DB_USER
            value: tapis_sys
          - name: TAPIS_SITE_ID
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: site_id
          - name: TAPIS_TENANT_SVC_BASEURL
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: service_site_url
          - name: TAPIS_GLOBUS_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: systems-config
                key: globus_client_id
          - name: TAPIS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-systems-secrets
                key: postgres-password
          - name: TAPIS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-systems-secrets
                key: service-password
