resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: mlhub-models-migrator
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mlhub-models-migrator
      spec:
        template:
          spec:
            containers:
              - image: tapis/mlhub-models-migrator:26Q1
                imagePullPolicy: Always
                name: models-migrator
                resources: {}

