#!/bin/bash

echo "burnup security:"

mkdir -p {{ tapisdatadir }}/security
mkdir -p {{ tapisdatadir }}/security/postgres

python3 ../admin/util/parse_skexport -c security -d {{ tapisdatadir }}

docker compose up -d

