#!/bin/bash

# first ensure that the ./postgres/burnup script has been run.

#kubectl create configmap tenantsnewdb --from-file=new_db.sql

kubectl apply -f service.yml
kubectl apply -f api.yml 
#kubectl apply -f util.yml 
