#!/bin/bash

# Setup the PVC for postgres
kubectl apply -f pvc.yml

# Start postgres service.
# This establishes any externally accessible ports. Services configured with a NodePort.
# Typically services are not removed during burndown so the ports will remain the same.
kubectl apply -f service.yml

# Start postgres pod
kubectl apply -f deploy.yml

# Wait for postgres to finish coming up
kubectl wait --timeout=120s --for=condition=available deploy/notifications-postgres

# Initialize the DB
kubectl create configmap notifications-init-db-configmap --from-file notifications-init-db-sh
kubectl create -f notifications-init-db.yml
kubectl wait --timeout=120s --for=condition=complete job/notifications-init-db
