apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-postgres
spec:
  selector:
    matchLabels:
      app: notifications-postgres
  template:
    metadata:
      labels:
        app: notifications-postgres
    spec:
      containers:
      - name: notifications-postgres
        image: {{ notifications_postgres_image }}
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: PGDATA
          value: "/pgdata/data"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-notifications-secrets
              key: postgres-password
        volumeMounts:
        - name: notifications-pg-data
          mountPath: "/pgdata"
      volumes:
      - name: notifications-pg-data
        persistentVolumeClaim:
          claimName: {{notifications_postgres_pvc}}
