kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notifications-postgres-vol01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{notifications_storage_class}}
  resources:
    requests:
      storage: 20Gi

