#!/bin/bash

# Set up configmap for jobs
kubectl apply -f ../jobs-config.yml

# Start the queue readers.   
kubectl apply -f jobrdr-Recovery.yml
kubectl apply -f jobrdr-AltQueue.yml
kubectl apply -f jobrdr-DeadLetter.yml 
kubectl apply -f jobrdr-EventQueue.yml
kubectl wait --for=condition=available deploy/jobs-rdr-recovery
