#!/bin/bash

#if [ "$1" == "allofit" ]
#then
##  kubectl delete -f service.yml 
#fi

kubectl delete -f jobrdr-Recovery.yml
kubectl delete -f jobrdr-AltQueue.yml
kubectl delete -f jobrdr-DeadLetter.yml
