apiVersion: batch/v1
kind: Job
metadata:
  name: apps-init-db
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: apps-init-db
        image: {{ apps_postgres_image }}
        imagePullPolicy: Always
        command: ["/tmp/apps-init-db-sh"]
        volumeMounts:
        - name: apps-init-db-vol
          mountPath: /tmp
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-apps-secrets
              key: postgres-password
        - name: MONITOR_PASSWORD
          value: 60f0c5bf8ed23120fc60
      volumes:
      - name: apps-init-db-vol
        configMap:
          name: apps-init-db-configmap
          defaultMode: 0777
  backoffLimit: 4
