kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apps-postgres-16-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{apps_storage_class}}
  resources:
    requests:
      storage: 20Gi
